repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      args: [--skip-string-normalization]
      language_version: python3.10
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.2.0
    hooks:
    -   id: reorder-python-imports
